use [relearn-angular-db]

CREATE USER EF_MIGRATION_RUNNER FOR LOGIN EF_MIGRATION_RUNNER;  
GO   

CREATE ROLE EF_MIGRATION_RUNNER_ROLE 

GRANT CONTROL ON DATABASE::[relearn-angular-db] TO EF_MIGRATION_RUNNER_ROLE
GRANT CREATE TABLE ON DATABASE::[relearn-angular-db] TO EF_MIGRATION_RUNNER_ROLE
GRANT CREATE FUNCTION ON DATABASE::[relearn-angular-db] TO EF_MIGRATION_RUNNER_ROLE
GRANT CREATE PROCEDURE ON DATABASE::[relearn-angular-db] TO EF_MIGRATION_RUNNER_ROLE
GRANT CREATE VIEW ON DATABASE::[relearn-angular-db] TO EF_MIGRATION_RUNNER_ROLE


ALTER ROLE EF_MIGRATION_RUNNER_ROLE add member EF_MIGRATION_RUNNER
