on: [push, workflow_dispatch]
name: Azure ARM
jobs:
  deploy-azure-resources:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - name: az login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
    - name: deploy resources
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        template: ./IaC/main.bicep
        failOnStdErr: false
        scope: 'subscription'
        region: eastus

  build-web-app:
    runs-on: ubuntu-latest
    needs: deploy-azure-resources

    steps:
      - uses: actions/checkout@main

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o publish/relearnAngularApi.App

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: publish/relearnAngularApi.App

        # Generate idempotent SQL Scripts for our migrations
      - name: Generate Migrations Scripts
        run: |
            dotnet tool install --global dotnet-ef
            dotnet tool restore
            dotnet ef migrations script -o ./script.sql -i -p ./RelearnAngularApi/

        #Deploy Script file
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .sqlScript
          path: ./script.sql

  deploy-web-app:
    runs-on: ubuntu-latest
    needs: build-web-app
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app
      
      # Log into Azure
      - name: az login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'relearn-angular-app'
          package: .
      
      - name: Download artifact from migrations scripts
        uses: actions/download-artifact@v3
        with:
          name: .sqlScript
          
      - uses: azure/sql-action@v2.2.1
        with:        
          connection-string: ${{ secrets.AZURE_SQL_EF_MIGRATION_RUNNER_CONNECTION_STRING }}
          path: ./script.sql
        